USE PersonalBlog
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name='PostTags')
DROP TABLE PostTags
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name='Tags')
DROP TABLE Tags
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name='Posts')
DROP TABLE Posts
GO

IF EXISTS(SELECT * FROM sys.tables WHERE Name='Categories')
DROP TABLE Categories
GO

CREATE TABLE Categories(
CategoryId INT PRIMARY KEY IDENTITY,
CategoryName NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Posts(
PostId INT PRIMARY KEY IDENTITY,
PostTitle NVARCHAR(100) NOT NULL,
PostBody NVARCHAR,
IsApproved BIT NOT NULL,
CreatedDate DATETIME2 DEFAULT (GETDATE()),
CategoryId INT FOREIGN KEY REFERENCES Categories(CategoryId),
ImageFileName NVARCHAR(100)
)
GO

CREATE TABLE Tags(
TagId INT PRIMARY KEY IDENTITY,
TagName NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE PostTags(
PostId INT NOT NULL FOREIGN KEY REFERENCES Posts(PostId),
TagId INT FOREIGN KEY REFERENCES Tags(TagId),
PRIMARY KEY (PostId,TagId)
)
GO